data = [
    {"link": "https://freelancer-uz.vercel.app", "title": "ZIRO"},
    {"link": "https://payments-uz.vercel.app", "title": "Payments app"},
    {"link": "https://my-notes-uz.vercel.app", "title": "MyNotes"},
    {"link": "https://calculatoruz.vercel.app", "title": "Calculator"},
    {"link": "https://dark-lamps.vercel.app", "title": "Dark Lamps"},
    {"link": "https://furniture-uz.vercel.app", "title": "Furniture"},
    {"link": "https://gotrip-uz.vercel.app", "title": "GoTriep"},
    {"link": "https://dashboard-uz.vercel.app", "title": "Dashboard"},
    {"link": "https://interior-market-uz.vercel.app", "title": "Interior Market"},
    {"link": "https://interior-uz.vercel.app", "title": "InteriorQU"},
    {"link": "https://taylors-portfolio-from-asliddin.vercel.app", "title": "Taylor's Portfolio"},
    {"link": "https://scandleted.vercel.app", "title": "Scandleted"},
    {"link": "https://qrcode-uz.vercel.app", "title": "Qr Code Generator"},
    {"link": "https://random-uz.vercel.app", "title": "Universal Randomer"},
    {"link": "https://quizapp-uz.vercel.app", "title": "Quiz App (Demo)"},
    {"link": "https://bookshelf-uz.vercel.app", "title": "BookShelf"},
]
